/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  planSidebar: [
    "intro",
    {
      type: "category",
      label: "🏗️ Fundamentos",
      items: [
        "01-fundamentos/tesis-central",
        "01-fundamentos/diagnostico",
        "01-fundamentos/fase-0-emergencia",
      ],
    },
    {
      type: "category",
      label: "⛽ Motor Financiero",
      items: [
        "02-motor-financiero/contratos-forward",
        "02-motor-financiero/fondo-soberano",
        "02-motor-financiero/deuda",
        "02-motor-financiero/inversion-inicial-fuentes",
        "02-motor-financiero/transicion-fiscal",
        "02-motor-financiero/enfermedad-holandesa",
        "02-motor-financiero/cashflow-20-trimestres",
        "02-motor-financiero/citgo",
      ],
    },
    {
      type: "category",
      label: "🤝 Ciudadanos y Diáspora",
      items: [
        "03-ciudadanos/inversion-ciudadana",
        "03-ciudadanos/diaspora",
        "03-ciudadanos/retorno-diaspora",
        "03-ciudadanos/los-que-se-quedaron",
      ],
    },
    {
      type: "category",
      label: "🛡️ Gobernanza y Seguridad",
      items: [
        "04-gobernanza/sistema-antifragil",
        "04-gobernanza/anticorrupcion-checklist",
        "04-gobernanza/geopolitica",
        "04-gobernanza/estado-derecho-moneda",
        "04-gobernanza/seguridad-fisica",
        "04-gobernanza/modelo-estado",
        "04-gobernanza/justicia-transicional",
        "04-gobernanza/blindaje-integridad",
        "04-gobernanza/roadmap-sanciones",
        "04-gobernanza/cuba-desconexion",
      ],
    },
    {
      type: "category",
      label: "🚀 Transformación",
      items: [
        "05-transformacion/hubs-tech",
        "05-transformacion/startup-programs",
        "05-transformacion/diversificacion",
        "05-transformacion/impacto-ia",
        "05-transformacion/educacion",
        "05-transformacion/comercio-exterior",
        "05-transformacion/capital-humano",
        "05-transformacion/oportunidades-negocio",
        "05-transformacion/oportunidades-empresas",
      ],
    },
    {
      type: "category",
      label: "🏛️ Estado y Servicios",
      items: [
        "06-realidad/estado-digital",
        "06-realidad/servicios-publicos",
        "06-realidad/infraestructura-basica",
        "06-realidad/esg-ejecucion",
        "06-realidad/pensiones-seguridad-social",
        "06-realidad/sistema-financiero",
        "06-realidad/infraestructura-calidad",
      ],
    },
    {
      type: "category",
      label: "📊 Ejecución y Proyecciones",
      items: [
        "07-ejecucion/kpis-activacion",
        "07-ejecucion/timeline",
        "07-ejecucion/proyecciones",
        "07-ejecucion/riesgos",
        "07-ejecucion/el-sueno",
        "07-ejecucion/equipo-ejecutor",
        "07-ejecucion/evaluacion-perspectivas",
      ],
    },
    {
      type: "category",
      label: "💡 Oportunidades de Inversión",
      items: [
        "10-oportunidades/modelo-concesiones",
        "10-oportunidades/data-centers-ia",
        "10-oportunidades/minerales-criticos",
        "10-oportunidades/capacidad-electrica",
        "10-oportunidades/energia-renovable",
        "10-oportunidades/agua-saneamiento",
        "10-oportunidades/telecomunicaciones",
        "10-oportunidades/turismo",
        "10-oportunidades/agro-ganaderia",
        "10-oportunidades/vialidad-logistica",
        "10-oportunidades/transporte-maritimo",
        "10-oportunidades/aviacion-aeropuertos",
        "10-oportunidades/fintech-banca-digital",
        "10-oportunidades/salud-telemedicina",
        "10-oportunidades/educacion-edtech",
        "10-oportunidades/construccion-inmobiliaria",
        "10-oportunidades/manufactura-industrial",
        "10-oportunidades/petroleo-gas",
      ],
    },
    {
      type: "category",
      label: "📎 Anexo: Para Inversionistas",
      items: [
        "08-pitch/resumen-ejecutivo",
        "08-pitch/business-model-canvas",
        "08-pitch/tam-sam-som",
        "08-pitch/yc-application",
        "08-pitch/pitch-deck",
      ],
    },
    {
      type: "category",
      label: "📎 Annex: For Investors",
      items: [
        "09-investors/executive-summary",
        "09-investors/business-model-canvas",
        "09-investors/tam-sam-som",
        "09-investors/yc-application",
        "09-investors/pitch-deck",
      ],
    },
    "glosario",
    "referencias",
    "conclusion",
  ],
};

module.exports = sidebars;
