/**
 * Chapter definitions for Venezuela S.A. PWA.
 * Maps sidebars.js structure to navigable book chapters.
 *
 * IMPORTANT: Each doc belongs to exactly ONE chapter.
 * Cross-referenced docs (e.g., 10-oportunidades/petroleo-gas appearing
 * in Motor Financiero sidebar) live ONLY in the oportunidades chapter.
 */

export const chapters = [
  {
    slug: 'introduccion',
    title: 'Venezuela S.A.',
    icon: 'BookOpen',
    description: 'Plan de Reconstruccion Nacional',
    hookStat: '40M accionistas',
    docs: ['intro'],
    visible: true,
    isSeparateSection: false,
  },
  {
    slug: 'fundamentos',
    title: 'Fundamentos',
    icon: 'Building2',
    description: 'Diagnostico + Fase 0 emergencia',
    hookStat: '303B barriles',
    docs: [
      '01-fundamentos/tesis-central',
      '01-fundamentos/diagnostico',
      '01-fundamentos/fase-0-emergencia',
    ],
    visible: true,
    isSeparateSection: false,
  },
  {
    slug: 'motor-financiero',
    title: 'Motor Financiero',
    icon: 'Banknote',
    description: 'Forwards, fondo soberano, deuda, inversion, fiscal',
    hookStat: 'USD 550-750B',
    docs: [
      '02-motor-financiero/contratos-forward',
      '02-motor-financiero/fondo-soberano',
      '02-motor-financiero/deuda',
      '02-motor-financiero/inversion-inicial-fuentes',
      '02-motor-financiero/transicion-fiscal',
      '02-motor-financiero/enfermedad-holandesa',
      '02-motor-financiero/cashflow-20-trimestres',
      '02-motor-financiero/citgo',
    ],
    visible: true,
    isSeparateSection: false,
  },
  {
    slug: 'ciudadanos',
    title: 'Ciudadanos y Diaspora',
    icon: 'Users',
    description: 'Inversion ciudadana, diaspora, retorno',
    hookStat: '7.9M en la diaspora',
    docs: [
      '03-ciudadanos/inversion-ciudadana',
      '03-ciudadanos/diaspora',
      '03-ciudadanos/retorno-diaspora',
      '03-ciudadanos/los-que-se-quedaron',
    ],
    visible: true,
    isSeparateSection: false,
  },
  {
    slug: 'gobernanza',
    title: 'Gobernanza y Seguridad',
    icon: 'Shield',
    description: 'Anticorrupcion, seguridad, modelo estado',
    hookStat: '34 -> 15 ministerios',
    docs: [
      '04-gobernanza/sistema-antifragil',
      '04-gobernanza/anticorrupcion-checklist',
      '04-gobernanza/geopolitica',
      '04-gobernanza/estado-derecho-moneda',
      '04-gobernanza/seguridad-fisica',
      '04-gobernanza/modelo-estado',
      '04-gobernanza/justicia-transicional',
      '04-gobernanza/blindaje-integridad',
      '04-gobernanza/roadmap-sanciones',
      '04-gobernanza/cuba-desconexion',
      '04-gobernanza/estrategia-china',
    ],
    visible: true,
    isSeparateSection: false,
  },
  {
    slug: 'transformacion',
    title: 'Transformacion',
    icon: 'Rocket',
    description: 'Hubs tech, startups, diversificacion, IA, educacion',
    hookStat: '5 hubs tech',
    docs: [
      '05-transformacion/hubs-tech',
      '05-transformacion/startup-programs',
      '05-transformacion/diversificacion',
      '05-transformacion/impacto-ia',
      '05-transformacion/educacion',
      '05-transformacion/comercio-exterior',
      '05-transformacion/capital-humano',
      '05-transformacion/oportunidades-negocio',
      '05-transformacion/oportunidades-empresas',
    ],
    visible: true,
    isSeparateSection: false,
  },
  {
    slug: 'realidad',
    title: 'Estado y Servicios',
    icon: 'Zap',
    description: 'Estado digital, servicios publicos, infraestructura',
    hookStat: '18,000 MW Caroni',
    docs: [
      '06-realidad/estado-digital',
      '06-realidad/servicios-publicos',
      '06-realidad/infraestructura-basica',
      '06-realidad/esg-ejecucion',
      '06-realidad/pensiones-seguridad-social',
      '06-realidad/sistema-financiero',
      '06-realidad/infraestructura-calidad',
    ],
    visible: true,
    isSeparateSection: false,
  },
  {
    slug: 'ejecucion',
    title: 'Ejecucion y Proyecciones',
    icon: 'CalendarCheck',
    description: 'KPIs, timeline, proyecciones, riesgos',
    hookStat: '15 anos',
    docs: [
      '07-ejecucion/kpis-activacion',
      '07-ejecucion/timeline',
      '07-ejecucion/proyecciones',
      '07-ejecucion/riesgos',
      '07-ejecucion/el-sueno',
      '07-ejecucion/equipo-ejecutor',
      '07-ejecucion/evaluacion-perspectivas',
    ],
    visible: true,
    isSeparateSection: false,
  },
  {
    slug: 'conclusion',
    title: 'Conclusion',
    icon: 'Flag',
    description: 'El Sueno de Venezuela',
    hookStat: 'El Sueno',
    docs: ['conclusion'],
    visible: true,
    isSeparateSection: false,
  },
  {
    slug: 'oportunidades',
    title: 'Oportunidades de Inversion',
    icon: 'Lightbulb',
    description: '20 sectores de inversion',
    hookStat: '20 sectores',
    docs: [
      '10-oportunidades/data-centers-ia',
      '10-oportunidades/minerales-criticos',
      '10-oportunidades/energia-renovable',
      '10-oportunidades/turismo',
      '10-oportunidades/agro-ganaderia',
      '10-oportunidades/transporte-maritimo',
      '10-oportunidades/aviacion-aeropuertos',
      '10-oportunidades/fintech-banca-digital',
      '10-oportunidades/construccion-inmobiliaria',
      '10-oportunidades/manufactura-industrial',
      '10-oportunidades/transporte-urbano',
      '10-oportunidades/petroleo-gas',
      '10-oportunidades/modelo-concesiones',
      '10-oportunidades/educacion-edtech',
      '10-oportunidades/negocios-voucher-educativo',
      '10-oportunidades/salud-telemedicina',
      '10-oportunidades/capacidad-electrica',
      '10-oportunidades/agua-saneamiento',
      '10-oportunidades/telecomunicaciones',
      '10-oportunidades/vialidad-logistica',
    ],
    visible: true,
    isSeparateSection: true,
  },
];

// Per D-06: hidden until Phase 5
export const hiddenChapters = ['08-pitch', '09-investors'];

// Standalone pages (not in chapter navigation, linked from landing)
export const standalonePages = [
  { slug: 'glosario', title: 'Glosario', doc: 'glosario' },
  { slug: 'referencias', title: 'Referencias', doc: 'referencias' },
];
